name: Question
description: Ask a question or get help
type: Question
body:
  - type: markdown
    attributes:
      value: |
        ## Question

        Use this form to ask a question about pipecat.

  - type: markdown
    attributes:
      value: |
        ### Environment (if applicable)

  - type: input
    id: pipecat-mcp-server-version
    attributes:
      label: Pipecat MCP Server version
      description: Which Pipecat MCP Server version are you using?
      placeholder: e.g., 0.0.1
    validations:
      required: true

  - type: input
    id: pipecat-version
    attributes:
      label: Pipecat version
      description: Which Pipecat version are you using?
      placeholder: e.g., 0.0.81
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Which Python version are you using? (if applicable)
      placeholder: e.g., 3.12.8
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using? (if applicable)
      placeholder: e.g., Ubuntu 24.04, Windows 11, macOS 12.5
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g., Chrome 139.0.7258.127
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Provide your question in detail here.
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What I've tried
      description: Describe what you've already tried or research you've done.
      placeholder: I've looked at the documentation and tried...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context or information that might help others understand your question better.
    validations:
      required: false
